var stores = ["Aaron's Archery Appendages",
"Aemad's Adventuring Supplies",
"Aggie",
"Agmundi Quality Clothes",
"Ak-Haranu's Exotic Shop",
"Al Kharid General Store",
"Alain -Farmer-",
"Aleck's Hunter Emporium",
"Ali the Carter",
"Ali the dyer",
"Ali the Kebab Seller",
"Ali's Discount Wares",
"Ali's Discount Wares Blackjack(d)",
"Ali's Discount Wares Blackjack(o)",
"Ali's Discount Wares Desert Clothes",
"Ali's Discount Wares Menap Clothes",
"Ali's Discount Wares Runes -Small-",
"Ali's Rune Shop",
"Alice's Farming Shop",
"Apothecary",
"Archery Competition",
"Ardougne Bakers Stall",
"Ardougne Fur Stall",
"Ardougne Gem Stall",
"Ardougne Silver Stall",
"Ardougne Spice Stall",
"Arhein's shop",
"Armour Shop",
"Armour Store (Blast Furnace)",
"Armoury",
"Arnold's Eclectic Supplies",
"Aubury's Rune Shop",
"Aurel's Supplies",
"Authentic Throwing Weapons",
"Ava's Odds and Ends",
"Ayleth Beaststalker's Hunting Suppl",
"Baba Yaga’s Magic Shop",
"Bandit Bargains",
"Bandit Camp Bar",
"Bandit Duty Free",
"Baraek's Fur Shop",
"Barker's Haberdashery",
"Battle Runes",
"Beefy Bill's Supplies",
"Bettamax's Shop",
"Betty's Magic Emporium",
"Blackjack Seller",
"Blades By Urbi",
"Blue Moon Inn",
"Blurberry Bar",
"Bob's Axes (repair)",
"Bob's Brilliant Axes",
"Bolkoy's Village Shop",
"Bolongo -Farmer-",
"Brian's Archery Shop",
"Brian's Battleaxe Bazaar",
"Brimhaven Agility Ticket Exchange",
"Brimhaven Dungeon",
"Buy first ancient staff",
"Buy Kittens",
"Buy New Crystal Equipment",
"Candle Seller",
"Candle Shop",
"Cap'n Izzy No-Beard",
"Carefree Crafting Stall",
"Carwen Essencebinder Magical Runes",
"Cassie's shield shop",
"Castle Wars Ticket Exchange",
"Charter Ships",
"Commander Loman's reward shop",
"Commendation Rewards",
"Construction Supplies",
"Contraband Yak Produce",
"Corporal Boothe's Armoury",
"Crossbow Shop -1-",
"Crossbow Shop -2-",
"Crossbow Shop -3-",
"Crystal Seed Recharges",
"Culinaromancer's Chest(Food)",
"Culinaromancer's Chest(Items)",
"Daemonheim Rewards",
"Daga's Scimitar Smithy",
"Dal's General Ogre Supplies",
"Dancing Donkey Inn",
"Dantaera -Farmer-",
"Dargaud's Bow and Arrows",
"Darren's Wilderness Cape Shop",
"Davon's Amulet Store",
"Dealga's Scimitar Emporium",
"Diango's Toy Store",
"Dodgy Derek's Dirty Deals",
"Dodgy Mike's Second Hand Clothing",
"Dommik's Crafting Shop",
"Dorgesh-Kaan General Supplies",
"Draynor Seed Market",
"Dreven -Farmer-",
"Drogo's Mining Emporium",
"Durgok",
"Dwarven Shopping Store",
"Edgeville General Store",
"Edmond's Wilderness Cape Shop",
"Edward's Wilderness Cape Shop",
"Ellena -Farmer-",
"Elnock's Backup Supply",
"Elstan -Farmer-",
"Enchant Battlestaves",
"Eniola's Banking Shop",
"Estate agent -Ardougne-",
"Etceteria Fish",
"Fairy Nuff",
"Falador General Store",
"Fancy Clothes Store",
"Fancy dress shop(hunter)",
"Faruq's Tools for Games",
"Fayeth -Farmer-",
"Fernahei's Fishing Hut",
"Fishing Guild Shop",
"Fist of Guthix Reward Shop",
"Flosi's Fishmongers",
"Flower Girl",
"Flying Horse Inn",
"Flynn's Mace Shop",
"Fortunato's Fine Wine",
"Francis -Farmer-",
"Freda's Boots",
"Fremennik Fishmonger",
"Fremennik Fur Trader",
"Frenita's Fine Cookery Shop",
"Fresh Meat",
"Frincos' Fabulous Herb Store",
"Frizzy Skernip -Farmer-",
"Funch's Fine Groceries",
"Gabooty's Tai Bwo Wannai Co-op",
"Gabooty's Tai Bwo Wannai Drink Shop",
"Gaius's Two handed shop",
"Garden Centre",
"Gardener Gunnhild",
"Garth -Farmer-",
"Gem Trader",
"General Store -Canifis-",
"Gerrant's Fishy Business",
"Gianne's Restaurant",
"Gift Shop",
"Gileth -Farmer-",
"Grand Tree Groceries",
"Green Gemstone Gems",
"Greengrocer of Miscellania",
"Grud's Herblore Stall",
"Grum's Gold Exchange",
"Gulluck and Sons",
"Gundik",
"Gunslik's Assorted Supplies",
"Hair of the Dog Tavern",
"Hairdresser's",
"Hamab's Crafting Emporium",
"Happy Heroes' H'emporium",
"Harpoon Joe's House of Rum",
"Harry's Fishing Shop",
"Herquin's Gems",
"Heskel -Farmer-",
"Hickton's Archery Emporium",
"Honest Jimmy's House of Stuff",
"Horvik's Armour Shop",
"Ian's Wilderness Cape Shop",
"Ifaba's General Store",
"Iffie's Random Costume Shop",
"Ignatius's Hot Deals",
"Initiate Temple Knight Armoury",
"Irksol",
"Island Fishmonger",
"Island Greengrocer",
"Jamila's Craft Stall",
"Jiminua's Jungle Store",
"Jolly Boar Inn",
"Jukat",
"Kaleb Paramaya",
"Karamja General Store",
"Karamja Wines, Spirits, and Beers",
"Kebab store",
"Kebab Store -Dwarf-",
"Keepa Kettilon's Store",
"Keldagrim Stonemason",
"Keldagrim's Best Bread",
"Khazard Bar",
"Khazard General Store",
"King's Axe Inn",
"Kragen -Farmer-",
"Lady of the Waves",
"Larry's Wilderness Cape Shop",
"Laughing Miner Pub",
"Leatherworker",
"Legends Guild General Store",
"Legends Guild Shop of Useful Items",
"Leon",
"Leprechaun Larry's Farming Supplies",
"Lletya Archery Shop",
"Lletya Food Store",
"Lletya General Store",
"Lletya Seamstress",
"Lord Marshal Brogan's reward shop",
"Louie's Armoured Legs Bazaar",
"Lovecraft's Tackle",
"Lowe's Archery Emporium",
"Lumbridge Fishing Supplies",
"Lumbridge General Store",
"Lundail's Arena-side Rune Shop",
"Lyra -Farmer-",
"Mage Arena Staffs",
"Mage Training Arena Shop",
"Magic Guild Store -Robes-",
"Magic Guild Store -Runes-",
"Make-over Mage",
"Markog",
"Martin Thwait's Lost and Found",
"Milk Seller -Falador-",
"Milk Seller -Lumbridge-",
"Milk Seller -Sinclair Mansion-",
"Miltog's Lamps",
"Miscellanian Clothes Shop",
"Miscellanian Food Shop",
"Miscellanian General Store",
"Mizgog's Amulet of Accuracy",
"Monkey Colony Banana Store",
"Monkey Colony Gem Store",
"Monkey Colony General Store",
"Moon Clan Fine Clothes",
"Moon Clan General Store",
"Mrs. Winkin's World of Seeds",
"Naff's Knockoff Staves",
"Nardah General Store",
"Nardah Hunter Shop",
"Nardok's Bone Weapons",
"Nathifa's Bake Stall",
"Neil's Wilderness Cape Shop",
"Neitiznot supplies",
"Newspaper Stand",
"Nulodion's Multicannon Parts",
"Nurmof's Pickaxe Shop",
"Obli's General Store",
"Ore Seller",
"Ore Shop",
"Oziach",
"Papa Mambo's Shop",
"Party Pete's Emporium",
"Party room",
"Patchy",
"Peksa's Helmet shop",
"Pelters' Veg Stall -Seers-",
"Pelters' Veg Stall -Varrock-",
"Pelters' Veg Stall -Yanille-",
"Pet Shop (Taverley)",
"Pet Shop (Yanille)",
"Pickaxe-Is-Mine",
"Pie Shop",
"Poison Arrow pub",
"Poletax's Herblore Shop",
"Pollnivneach general store",
"Polypore Dungeon Supplies",
"Port Phasmatys General Store",
"Quality Armour Shop",
"Quality Weapons Shop",
"Quartermaster's Stores",
"Raetul and Co's Cloth Store",
"Ranael's Super Skirt Store",
"Ranging Guild Ticket Exchange",
"Rasolo the Wandering Merchant",
"Razmire Builders Merchants",
"Razmire General Store",
"Re-enchant elf crystal",
"Reinald's Smithing Emporium",
"Reldak's Leather Armour",
"Rellekka Longhall Bar",
"Repair Iban Staff",
"Replace helm of Neitiznot",
"Rewards -Livid Farm-",
"Rhazien -Farmer-",
"Rhonen -Farmer-",
"Richard's Farming Shop",
"Richard's Wilderness Cape Shop",
"Rimmington General Store",
"Rising Sun Inn",
"Rogue",
"Rok's Chocs Box",
"Rometti's Fine Fashions",
"Rommik's Crafting Shop",
"Rufus' Meat Emporium",
"Runecrafting Guild Rewards",
"Rusty Anchor",
"Sam's Wilderness Cape Shop",
"Sandwich Lady Bakery",
"Sarah's Farming Shop",
"Sawmill Operator(Planks)",
"Scavvo's Rune Store",
"Seddu's Adventurer's Store",
"Selena -Farmer-",
"Sell Cats",
"Send Parcel",
"Serjeant Cole's reward shop",
"Servants",
"Shop of Distaste",
"Sigmund the Merchant",
"Silk Trader (desert)",
"Silk Trader (Stall)",
"Silver Cog Silver Stall",
"Simon's Wilderness Cape Shop",
"Skulgrimen's Battle Gear",
"Slayer Equipment -Ancient Cavern-",
"Slayer Equipment -Canifis-",
"Slayer Equipment -Edgeville-",
"Slayer Equipment -Pollnivneach-",
"Slayer Equipment -Shilo-",
"Slayer Equipment -Taverley-",
"Slayer Equipment -Zanaris-",
"Slayer Rewards -Ancient Cavern-",
"Slayer Rewards -Burthorpe-",
"Slayer Rewards -Canifis-",
"Slayer Rewards -Edgeville-",
"Slayer Rewards -Pollnivneach-",
"Slayer Rewards -Shilo-",
"Slayer Rewards -Zanaris-",
"Smithing Smith's Shop",
"Solihib's Food Shop",
"Stankers' Bronze Pickaxes",
"Stealing Creation Reward Shop",
"Strange Old Man",
"Summoning Supplies -Ogre-",
"Summoning Supplies -Swamp-",
"Summoning Supplies -Taverley-",
"Tamayu's Spear Stall",
"Tan hides -Canifis-",
"Tanner -Crafting Guild-",
"Tanner -Varrock-",
"Tanning shop",
"Taria -Farmer-",
"Taxidermist",
"The Asp and Snake Bar",
"The Dead Man's Chest",
"The Dragon Inn",
"The Esoterican Arms",
"The Forester's Arms",
"The Lighthouse Store",
"The Other Inn",
"The Pick and Lute",
"The Shrimp and Parrot",
"The Spice Is Right",
"Thessalia's Fine Clothes",
"Thessalia's Fine Clothes(Frog)",
"Thessalia's Fine Clothes(Makeover)",
"Tiadeche's Karambwan Stall",
"Tindar",
"Tony's Pizza Bases",
"Torrell -Farmer-",
"Trader Stan's Trading Post",
"Trader Sven's Black Market Goods",
"Trader's goods",
"Travel Rug Merchant",
"Treznor -Farmer-",
"Turgok",
"Tutab's Magical Market",
"TzHaar-Hur-Lek's Ore and Gem Store",
"TzHaar-Hur-Tel's Equipment Store",
"TzHaar-Mej-Roh's Rune Store",
"Uglug's Stuffsies",
"Urist's Crafting Supplies",
"Use furnace",
"Valaine's Shop of Champions",
"Vanessa's Farming Shop",
"Varrock General Store",
"Varrock Sword Shop",
"Vasquen -Farmer-",
"Vermundi's Clothing Stall",
"Vigr's Warhammers",
"Void Knight Archery Store",
"Void Knight General Store",
"Void Knight Magic Store",
"War-chief Reeves's reward shop",
"Warrior Guild Armoury",
"Warrior Guild Potion Shop",
"Warriors' Guild Food Shop",
"Wayne's Chains",
"Weapons Galore",
"West Ardougne General Store",
"White Knight's Armoury",
"William's Wilderness Cape Shop",
"Wizard Finix's Runecrafting Shop",
"Wydin's Food store",
"Wyson the Gardener",
"Yak Hide Tanner",
"Yaktwee's Invizzy Critters Stall",
"Ye Olde Tea Shoppe",
"Yrsa's Accoutrements",
"Zaff's Superior Staves",
"Zahur - Herblore Assistance",
"Zanaris General Store",
"Zeke's Superior Scimitars",
"Zenesha's Platebody Shop",
"Zenkog"];